INSERT INTO pais (nombre_pais, continente) VALUES
('Afganistán', 'Asia'),
('Albania', 'Europa'),
('Alemania', 'Europa'),
('Andorra', 'Europa'),
('Angola', 'África'),
('Antigua y Barbuda', 'América'),
('Arabia Saudita', 'Asia'),
('Argelia', 'África'),
('Argentina', 'América'),
('Armenia', 'Asia'),
('Australia', 'Oceanía'),
('Austria', 'Europa'),
('Azerbaiyán', 'Asia'),
('Bahamas', 'América'),
('Bangladés', 'Asia'),
('Barbados', 'América'),
('Baréin', 'Asia'),
('Bélgica', 'Europa'),
('Belice', 'América'),
('Benín', 'África'),
('Bielorrusia', 'Europa'),
('Birmania', 'Asia'),
('Bolivia', 'América'),
('Bosnia y Herzegovina', 'Europa'),
('Botsuana', 'África'),
('Brasil', 'América'),
('Brunéi', 'Asia'),
('Bulgaria', 'Europa'),
('Burkina Faso', 'África'),
('Burundi', 'África'),
('Bután', 'Asia'),
('Cabo Verde', 'África'),
('Camboya', 'Asia'),
('Camerún', 'África'),
('Canadá', 'América'),
('Catar', 'Asia'),
('Chad', 'África'),
('Chile', 'América'),
('China', 'Asia'),
('Chipre', 'Europa'),
('Colombia', 'América'),
('Comoras', 'África'),
('Congo', 'África'),
('Corea del Norte', 'Asia'),
('Corea del Sur', 'Asia'),
('Costa de Marfil', 'África'),
('Costa Rica', 'América'),
('Croacia', 'Europa'),
('Cuba', 'América'),
('Dinamarca', 'Europa'),
('Dominica', 'América'),
('Ecuador', 'América'),
('Egipto', 'África'),
('El Salvador', 'América'),
('Emiratos Árabes Unidos', 'Asia'),
('Eritrea', 'África'),
('Eslovaquia', 'Europa'),
('Eslovenia', 'Europa'),
('España', 'Europa'),
('Estados Unidos', 'América'),
('Estonia', 'Europa'),
('Esuatini', 'África'),
('Etiopía', 'África'),
('Filipinas', 'Asia'),
('Finlandia', 'Europa'),
('Fiyi', 'Oceanía'),
('Francia', 'Europa'),
('Gabón', 'África'),
('Gambia', 'África'),
('Georgia', 'Asia'),
('Ghana', 'África'),
('Granada', 'América'),
('Grecia', 'Europa'),
('Guatemala', 'América'),
('Guyana', 'América'),
('Guinea', 'África'),
('Guinea-Bisáu', 'África'),
('Guinea Ecuatorial', 'África'),
('Haití', 'América'),
('Honduras', 'América'),
('Hungría', 'Europa'),
('India', 'Asia'),
('Indonesia', 'Asia'),
('Irak', 'Asia'),
('Irán', 'Asia'),
('Irlanda', 'Europa'),
('Islandia', 'Europa'),
('Islas Marshall', 'Oceanía'),
('Islas Salomón', 'Oceanía'),
('Israel', 'Asia'),
('Italia', 'Europa'),
('Jamaica', 'América'),
('Japón', 'Asia'),
('Jordania', 'Asia'),
('Kazajistán', 'Asia'),
('Kenia', 'África'),
('Kirguistán', 'Asia'),
('Kiribati', 'Oceanía'),
('Kuwait', 'Asia'),
('Laos', 'Asia'),
('Lesoto', 'África'),
('Letonia', 'Europa'),
('Líbano', 'Asia'),
('Liberia', 'África'),
('Libia', 'África'),
('Liechtenstein', 'Europa'),
('Lituania', 'Europa'),
('Luxemburgo', 'Europa'),
('Madagascar', 'África'),
('Malasia', 'Asia'),
('Malaui', 'África'),
('Maldivas', 'Asia'),
('Malí', 'África'),
('Malta', 'Europa'),
('Marruecos', 'África'),
('Mauricio', 'África'),
('Mauritania', 'África'),
('México', 'América'),
('Micronesia', 'Oceanía'),
('Moldavia', 'Europa'),
('Mónaco', 'Europa'),
('Mongolia', 'Asia'),
('Montenegro', 'Europa'),
('Mozambique', 'África'),
('Namibia', 'África'),
('Nauru', 'Oceanía'),
('Nepal', 'Asia'),
('Nicaragua', 'América'),
('Níger', 'África'),
('Nigeria', 'África'),
('Noruega', 'Europa'),
('Nueva Zelanda', 'Oceanía'),
('Omán', 'Asia'),
('Países Bajos', 'Europa'),
('Pakistán', 'Asia'),
('Palaos', 'Oceanía'),
('Palestina', 'Asia'),
('Panamá', 'América'),
('Papúa Nueva Guinea', 'Oceanía'),
('Paraguay', 'América'),
('Perú', 'América'),
('Polonia', 'Europa'),
('Portugal', 'Europa'),
('Reino Unido', 'Europa'),
('República Centroafricana', 'África'),
('República Checa', 'Europa'),
('República Democrática del Congo', 'África'),
('República Dominicana', 'América'),
('Ruanda', 'África'),
('Rumania', 'Europa'),
('Rusia', 'Europa'),
('Samoa', 'Oceanía'),
('San Cristóbal y Nieves', 'América'),
('San Marino', 'Europa'),
('San Vicente y las Granadinas', 'América'),
('Santa Lucía', 'América'),
('Santo Tomé y Príncipe', 'África'),
('Senegal', 'África'),
('Serbia', 'Europa'),
('Seychelles', 'África'),
('Sierra Leona', 'África'),
('Singapur', 'Asia'),
('Siria', 'Asia'),
('Somalia', 'África'),
('Sri Lanka', 'Asia'),
('Suazilandia', 'África'),
('Sudáfrica', 'África'),
('Sudán', 'África'),
('Sudán del Sur', 'África'),
('Suecia', 'Europa'),
('Suiza', 'Europa'),
('Surinam', 'América'),
('Tailandia', 'Asia'),
('Tanzania', 'África'),
('Tayikistán', 'Asia'),
('Timor Oriental', 'Asia'),
('Togo', 'África'),
('Tonga', 'Oceanía'),
('Trinidad y Tobago', 'América'),
('Túnez', 'África'),
('Turkmenistán', 'Asia'),
('Turquía', 'Asia'),
('Tuvalu', 'Oceanía'),
('Ucrania', 'Europa'),
('Uganda', 'África'),
('Uruguay', 'América'),
('Uzbekistán', 'Asia'),
('Vanuatu', 'Oceanía'),
('Vaticano', 'Europa'),
('Venezuela', 'América'),
('Vietnam', 'Asia'),
('Yemen', 'Asia'),
('Yibuti', 'África'),
('Zambia', 'África'),
('Zimbabue', 'África');