DROP SCHEMA IF EXISTS museo_ciclomotor;

CREATE SCHEMA museo_ciclomotor CHARSET latin1 COLLATE latin1_general_ci;

USE museo_ciclomotor;

CREATE TABLE moto(
  id_moto INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  modelo VARCHAR(20) NOT NULL,
  año NUMERIC NULL,
  color VARCHAR(20) NOT NULL,
  historia VARCHAR(1000) NULL,
  tipo VARCHAR(20) NULL,
  marca_id INTEGER NOT NULL
) ENGINE InnoDB;

CREATE TABLE imagen(
  id_imagen INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ruta_imagen VARCHAR(500) NOT NULL,
  moto_id INTEGER NULL
) ENGINE InnoDB;

CREATE TABLE marca(
  id_marca INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(20) NOT NULL,
  pais_id INTEGER NOT NULL
) ENGINE InnoDB;

CREATE TABLE pais(
  id_pais INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre_pais VARCHAR(50) NOT NULL,
  continente VARCHAR(20) NOT NULL
) ENGINE InnoDB;

CREATE TABLE comentario(
  id_comentario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  usuario_id INTEGER NOT NULL,
  moto_id INTEGER NOT NULL,
  texto VARCHAR(1000) NOT NULL,
  puntuacion NUMERIC NULL,
  fecha TIMESTAMP NOT NULL
) ENGINE InnoDB;

CREATE TABLE usuarios(
  id_usuario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  usuario VARCHAR(20) NOT NULL,
  email VARCHAR(30) NOT NULL,
  contraseña VARCHAR(50) NOT NULL,
  administrador VARCHAR(20) NOT NULL DEFAULT FALSE
) ENGINE InnoDB;

CREATE TABLE favoritos(
  id_favoritos INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  fecha TIMESTAMP NOT NULL,
  usuario_id INTEGER NOT NULL,
  moto_id INTEGER NOT NULL
) ENGINE InnoDB;

ALTER TABLE moto
  ADD FOREIGN KEY (marca_id) REFERENCES marca(id_marca) ON DELETE RESTRICT ON UPDATE RESTRICT;
  
ALTER TABLE imagen
  ADD FOREIGN KEY (moto_id) REFERENCES moto(id_moto) ON DELETE RESTRICT ON UPDATE RESTRICT;
  
ALTER TABLE marca
  ADD FOREIGN KEY (pais_id) REFERENCES pais(id_pais) ON DELETE RESTRICT ON UPDATE RESTRICT;
  
ALTER TABLE comentario
  ADD FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD FOREIGN KEY (moto_id) REFERENCES moto(id_moto) ON DELETE RESTRICT ON UPDATE RESTRICT;
  
ALTER TABLE favoritos
  ADD FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD FOREIGN KEY (moto_id) REFERENCES moto(id_moto) ON DELETE RESTRICT ON UPDATE RESTRICT;